fix: #107
Astromations/Hazy pull request #112
Opened 2024-06-30 15:30 UTC by sanoojes

I think it should fix the issue with the update the links are of the main css and js files not the remote ones as marketplace updates them in app start and those links are from the pages deployment

2024-06-30 22:11 UTC, hbishere requested changes

2024-06-30 22:11 UTC, hbishere commented on manifest.json
> +  "include": ["https://astromations.github.io/Hazy/hazy.js"],
I think this has to be theme.js since that's what Spicetify searches for

2024-06-30 22:28 UTC, Astromations commented
Alright, let's give it a try.

2024-06-30 22:29 UTC, merged

2024-07-01 14:44 UTC, sanoojes commented
yeah